### ISSUE TITLE
No callbacks when using range.insertNode

### ISSUE THREAD

**Issue by ribrdb** [webcomponents/custom-elements#162] opened 2018-07-03 21:22 UTC
Using the polyfill on Edge, if I insert a custom node with range.insertNode, the connectedCallback never runs.
I tried creating the node with document.createElement or by new MyCustomElement, no callbacks run in either case.

**Comment by azakus** [comment] 2019-06-07 23:27
Duplicate of https://github.com/webcomponents/polyfills/issues/74

**Closed by azakus** 2019-06-07 23:27 UTC
