### ISSUE TITLE
Modifying DOM in connectedCallback leads to wrong callback order for children.

### ISSUE THREAD

**Issue by Legioth** [webcomponents/custom-elements#158] opened 2018-05-29 09:27 UTC
When a custom element modifies its DOM structure from within `connectedCallback`, a child receives 
`disconnectedCallback` before `connectedCallback`. My test case simply removes the child, whereas a real-world case might e.g. add a wrapper around the child.

This can cause issues with e.g. Polymer elements that clean up things related to their `this.$` in `disconnectedCallback`.

Reproduced with http://jsbin.com/hofoyasure/edit?html,console,output

Expected output (as seen in Chrome):
```
"parent connected"
"child connected"
"child disconnected"
```

Observed output (as seen in e.g. Firefox 59.0.2)
```
"parent connected"
"child disconnected"
"child connected"
```

This issue is potentially related to https://github.com/webcomponents/custom-elements/issues/128.

**Comment by azakus** [comment] 2019-06-07 23:26
Closing as duplicate of https://github.com/webcomponents/polyfills/issues/107

**Closed by azakus** 2019-06-07 23:26 UTC
