### ISSUE TITLE
container.innerHTML = '' calls contained element's disconnectedCallback twice

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/custom-elements#129] opened 2017-12-22 18:48 UTC
The polyfill has an  `.innerHTML` bug on IE11.  The problem seems to be that shadyDOM adds its own `innerHTML` for IE11 which ends up calling `disconnectedCallback` and then custom-elements calls (redundantly) `disconnectedCallback` on the same element. 

```
      var container = document.createElement('div');
      document.body.appendChild(container);
      container.innerHTML = '<x-product data-img="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4621/python.png"></x-product>';
      container.innerHTML = '';
```

The assignment of `''` to `container.innerHTML` should only cause a single call to x-product's `disconnectedCallback`.

Reproduction (run on IE11):
https://jeff17robbins.github.io/wc-v1-retest/innerHTML_polyfill_debug.html

https://github.com/webcomponents/custom-elements/blob/76311bc2e7cd58b59ef641d6efa3536b05241f64/src/Patch/Element.js#L33

`baseDescriptor.set.call(this, htmlString);` in Element.js (shown in the code pasted below) calls what it thinks of as the "baseDescriptor's" `innerHTML`, but it ends up being a setter installed by shadyDOM and this setter calls shadyDOM's `clearNode` 

https://github.com/webcomponents/shadydom/blob/58da0c19dbf7544e3c7f3fa21f9396892b4ee476/src/patch-accessors.js#L348

which ends up calling `disconnectedCallback`:

>disconnectedCallback [Line: 107, Col: 13], innerHTML_polyfill_debug.html
disconnectedCallback [Line: 4451, Col: 9], webcomponents-lite-debug.js
disconnectTree [Line: 4331, Col: 11], webcomponents-lite-debug.js
Anonymous function [Line: 5035, Col: 7], webcomponents-lite-debug.js
clearNode [Line: 2185, Col: 5], webcomponents-lite-debug.js
innerHTML.set [Line: 2463, Col: 7], webcomponents-lite-debug.js
innerHTML.set [Line: 5278, Col: 9], webcomponents-lite-debug.js
Anonymous function [Line: 118, Col: 7], innerHTML_polyfill_debug.html
wrapperFn [Line: 3217, Col: 7], webcomponents-lite-debug.js
dispatchEvent$$1 [Line: 3995, Col: 5], webcomponents-lite-debug.js
Anonymous function [Line: 7580, Col: 5], webcomponents-lite-debug.js

```
   function patch_innerHTML(destination, baseDescriptor) {
    Object.defineProperty(destination, 'innerHTML', {
      enumerable: baseDescriptor.enumerable,
      configurable: true,
      get: baseDescriptor.get,
      set: /** @this {Element} */ function(htmlString) {
        const isConnected = Utilities.isConnected(this);

        // NOTE: In IE11, when using the native `innerHTML` setter, all nodes
        // that were previously descendants of the context element have all of
        // their children removed as part of the set - the entire subtree is
        // 'disassembled'. This work around walks the subtree *before* using the
        // native setter.
        /** @type {!Array<!Element>|undefined} */
        let removedElements = undefined;
        if (isConnected) {
          removedElements = [];
          Utilities.walkDeepDescendantElements(this, element => {
            if (element !== this) {
              removedElements.push(element);
            }
          });
        }

        baseDescriptor.set.call(this, htmlString);  //. <<< this calls shadyDOM's innerHTML hook on IE11

        if (removedElements) {
          for (let i = 0; i < removedElements.length; i++) {
            const element = removedElements[i];
            if (element.__CE_state === CEState.custom) {
              internals.disconnectedCallback(element);
            }
          }
        }
```

But then `internals.disconnectedCallback(element);` calls the element's `disconnectedCallback` *again*.

>disconnectedCallback [Line: 107, Col: 13], innerHTML_polyfill_debug.html
disconnectedCallback [Line: 4451, Col: 9], webcomponents-lite-debug.js
innerHTML.set [Line: 5284, Col: 15], webcomponents-lite-debug.js
Anonymous function [Line: 118, Col: 7], innerHTML_polyfill_debug.html
wrapperFn [Line: 3217, Col: 7], webcomponents-lite-debug.js
dispatchEvent$$1 [Line: 3995, Col: 5], webcomponents-lite-debug.js
Anonymous function [Line: 7580, Col: 5], webcomponents-lite-debug.js

**Comment by Jeff17Robbins** [comment] 2017-12-29 13:27
This is also an issue on MS Edge. 

custom-elements and shadydom are both trying to disconnect the element.  Assuming that custom-elements is meant to work either with or without shadydom, I'm not sure which module is responsible for this bug.

Naively, [this ](https://github.com/webcomponents/custom-elements/blob/76311bc2e7cd58b59ef641d6efa3536b05241f64/src/Patch/Element.js#L54)custom-elements code

```
        if (removedElements) {
          for (let i = 0; i < removedElements.length; i++) {
            const element = removedElements[i];
            if (element.__CE_state === CEState.custom) {
              internals.disconnectedCallback(element);
            }
          }
        }
```

could guard against the shadydom plugin already disconnecting by adding an `isConnected` test:

```
        if (removedElements) {
          for (let i = 0; i < removedElements.length; i++) {
            const element = removedElements[i];
            if (element.__CE_state === CEState.custom && element.isConnected) { // <<< test added
              internals.disconnectedCallback(element);
            }
          }
        }
```

but I don't know if there are other instances of this problem elsewhere in the code.



Some questions this bug raised for me:

1. Is shadydom meant to be optional?

2. If so, how is it meant to coordinate its accessor patches with custom-element's accessor patches? E.g., is custom-elements meant to assume it is calling the native innerHTML of the element, or is custom-elements supposed to guard against side effects of shadydom?  Or is shadydom meant to plug in non-disruptively?

3. Are there QA tests designed to check for erroneous extra calls to the lifecycle callbacks?

**Comment by TimvdLippe** [comment] 2017-12-29 21:48
@bicknellr I assume the reactions PR addresses this problem as well?

**Comment by bicknellr** [comment] 2018-01-04 00:20
This is an issue with how the polyfills wrap things: particularly, if each polyfill doesn't keep a direct reference to the getters / setters / functions it intends to wrap (from before they were wrapped and only ever calling into those), then it can't guarantee that it won't accidentally be called reentrantly by some other library wrapping the same thing (or do the same to any other library). #102 is meant to address this within the custom elements polyfill but this problem also exists in Shady DOM. In this case, it's the call to `removeChild` you found:

https://github.com/webcomponents/shadydom/blob/f6f28185b8c127af79b2a86f40612d9f1ca218d4/src/patch-accessors.js#L16-20

cc @sorvell

**Comment by Jeff17Robbins** [comment] 2018-01-04 02:47
@bicknellr, I'm probably missing something, but if both custom-elements and shadydom think they "own" `innerHTML`, and if, e.g., custom-elements `innerHTML` runs and avoids calling shadydom's `innerHTML`  as you suggest , how does shadydom's `innerHTML` ever run?  

I'm assuming shadydom's patch of `innerHTML` on IE11 is for a good reason, after all.

In other words, I see the bad implications of one hand not knowing what the other one is doing, but I don't see how making each polyfill ignore the other fixes that.

**Comment by bicknellr** [comment] 2018-01-04 23:01
It's not that they're ignoring each other, it's that they should be aware of the possibility that the APIs they use to do their own work might be modified by other polyfills later and that using the modified ones might be dangerous.

Consider some built-in API like this:
```javascript
window.Something = {f(){ /* ... */ }};
```
.. with two 'polyfills' like this (applied in this order):
```javascript
// #1: Implement `g` using `f`.
(() => {
  const wrapped_f = Something.f;
  Something.g = function() {
    // do things here...
    wrapped_f();
    // do more things here...
  };
})();

// #2: Add other effects during `f`.
(() => {
  const wrapped_f = Something.f;
  Something.f = function() {
    wrapped_f();
    alert('You called `Something.f`.');
  };
})();
```
The `g` polyfill always captures `Something.f` right as it starts up so it can be sure it always calls the same function.

Next, consider if the `g` polyfill was implemented like this instead:
```javascript
Something.g = function() {
  // do things here...
  this.f();
  // do more things here...
};
```

The `g` polyfill now ends up using whatever the last polyfill that modified `f` decided to replace it with, which could be a problem if the `g` polyfill doesn't know about `f`'s changed behavior or have an appropriate way to work around the fact that calling `this.f` will always do that modified behavior and not only what the original `Something.f` did.

The problem ends up being that Shady DOM and the custom elements polyfill both currently have a handful of places where they do something more like the second implementation of the `g` polyfill here - `clearNode` in Shady DOM being one of those.

**Comment by Jeff17Robbins** [comment] 2018-01-05 01:06
I apologize but I didn't follow you example.  custom-elements and shadydom each patch `innerHTML`.  Their patch implementations deal with different concerns, or overlapping concerns, or identical concerns.  I don't know which case it is.

But when I execute `container.innerHTML = '';` which of the two `innerHTML` implementations are supposed to be run?

If it is custom-elements` implementation, I understand why it would be correct for it to then call the original `innerHTML` it patched.

But why, then, does shadydom patch `innerHTML`?  When will its patch ever get called?  Or under what circumstances will its patch get called?  It the shadydom `innerHTML` only meant for elements within its simulated shadow DOM tree?  If so, then my issue reveals a bug in shadydom which shouldn't be patching `innerHTML` in the light DOM, or if it must (because how else?!), it should check if the element whose `innerHTML` is getting called is in light or shady DOM, shouldn't it?  But then you wouldn't want custom-elements' `innerHTML` called on a shady DOM element.

Obviously I'm confused.  But it would seem that if each polyfill (custom-elements and shadydom) are EACH patching every element's `innerHTML` then they need to coordinate between the two of them somehow.  Assuming that each one's patch of `innerHTML` is different from the other's.

**Comment by bicknellr** [comment] 2018-01-05 02:33
> But when I execute `container.innerHTML = '';` which of the two `innerHTML` implementations are supposed to be run?

Both polyfills wrap `innerHTML`: when you run `container.innerHTML = '';` you will be calling the setter added by the custom elements polyfill and that setter then calls the one added by Shady DOM [here](https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/Patch/Element.js#L52) or [here, if you're in a browser where the `innerHTML` descriptor is missing](https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/Patch/Element.js#L105) (IE, IIRC).

What's kind of weird is that, in that second link, the custom elements polyfill *does* overwrite another descriptor if it already exists on the instance.[1] However, it specifically implements `innerHTML` using [an element that hasn't been modified by anything applied after the custom elements polyfill](https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/Patch/Element.js#L103) so that it can get to the `innerHTML` implementation below it. (Which works due to the strange way that browsers with missing `innerHTML` descriptors implement it.)

[1] Is this related to what you're referring to? This might be worth calling a separate bug. Conveniently it shouldn't have any symptoms when this polyfill is used with Shady DOM. Possibly fixed by checking for a setter on the instance inside [the callback here](https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/Patch/Element.js#L81) and passing that as `baseDescriptor` to `patch_innerHTML` if it exists before falling back to the custom getter / setter.

> But why, then, does shadydom patch `innerHTML`? When will its patch ever get called? Or under what circumstances will its patch get called? Is the shadydom `innerHTML` only meant for elements within its simulated shadow DOM tree?

Maybe the earlier part of this response covers some of this? Could you clarify what you mean by "only meant for elements within its simulated shadow DOM tree"?

> If so, then my issue reveals a bug in shadydom which shouldn't be patching `innerHTML` in the light DOM, or if it must (because how else?!), it should check if the element whose `innerHTML` is getting called is in light or shady DOM, shouldn't it? But then you wouldn't want custom-elements' `innerHTML` called on a shady DOM element.

Yes, Shady DOM's `innerHTML` getter / setter does different things depending on where the element is. I'm not sure how Shady DOM could avoid wrapping those though.

**Comment by Jeff17Robbins** [comment] 2018-01-05 19:44
I remain completely confused.  

I see two patches of `innerHTML`.  They each take a related yet different strategy to deal with IE11's special behavior of not only orphaning the top-level children of the element whose `innerHTML` is being set, but **also** atomizing all the descendants.

So if you need to do something special (e.g. call `disconnectedCallback`) on each and every descendant, on IE11, you have to walk the descendants.  

custom-elements first walks the descendants to memorize them, then calls the previous definition of `innerHTML`, which if you include shadydom in your webcomponents polyfill, is the shadydom implementation of `innerHTML`.  Then custom-elements calls `disconnectedCallback` on all the elements it memorized.

shadydom takes a different approach to dealing with the IE11 problem.  It has a routine `clearNode` which calls `removeChild` on all the children.  Which in turn calls into custom-elements various patches, ending up calling `disconnectedCallback` first, before custom-elements gets to do it in its `innerHTML`.

I don't see how you can fix this problem without coordinating the two polyfills.  It doesn't seem logical that both polyfills (which are both needed on IE11) each have to solve the IE11 `innerHTML` atomization problem (in two different ways).  Only one blob of code should be responsible for dealing with that IE11 problem, and the one routine should only get called once.  The current situation has the tree walked twice.

I don't see how you can solve it simply by having the custom-elements implementation call the native `innerHTML` and ignore whatever needs shadydom has.  And I don't see how you can solve it by having the one polyfill call the other polyfill's implementation yet ignore what it is doing.

In your previous posting @bicknellr , I'm sorry but I couldn't understand how you think this problem should get disentangled.   My simple workaround is to have the custom-elements implementation of `innerHTML` defensively check `isConnected`, e.g.

```if (element.__CE_state === CEState.custom && element.isConnected) { // <<< test added```

which avoids needing a mechanism to coordinate itself with shadydom, and ensures it doesn't call `disconnectedCallback` on an element already disconnected, in this case, by shadydom.

I feel I must be missing something in your post that explains how you would fix this problem. To reiterate the problem statement:

on IE11

```
      var container = document.createElement('div');
      document.body.appendChild(container);
      container.innerHTML = '<x-product data-img="https://s3-us-west-2.amazonaws.com/s.cdpn.io/4621/python.png"></x-product>';
      container.innerHTML = '';
```

That last line's assignment of `''` to `container.innerHTML` is either meant to invoke custom-elements implementation or shadydom's or both.  

My confusion is how could it possibly work to invoke both (meaning custom-elements implementation of `innerHTML` in turn calls shadydom's implementation, perhaps erroneously thinking it is calling the native implementation of `innerHTML`?)

Yet if the assignment of `''` only called custom-elements implementation, shadydom doesn't get to do whatever it was it wanted to do by patching `innerHTML` in the first place!

So I feel like the two implementations need to coordinate somehow if they both need to do something.

And, furthermore, it seems unwise that they both are trying to deal with the IE11 "atomization" problem.  Surely, only one piece of code needs to do that?

**Comment by bicknellr** [comment] 2018-01-05 20:41
> It has a routine clearNode which calls removeChild on all the children. Which in turn calls into custom-elements various patches, ending up calling disconnectedCallback first, before custom-elements gets to do it in its innerHTML.

Exactly. This is the problem exhibited in your original post. `clearNode` should not be calling into the custom elements polyfill's `removeChild` wrapper.

> I don't see how you can solve it simply by having the custom-elements implementation call the native innerHTML and ignore whatever needs shadydom has.

The custom elements polyfill isn't skipping over Shady DOM's implementation of `innerHTML`, it's specifically making sure that it *only* calls into the one added by Shady DOM and not one which might have been modified by something applied after the custom elements polyfill.

> I don't see how you can fix this problem without coordinating the two polyfills. It doesn't seem logical that both polyfills (which are both needed on IE11) each have to solve the IE11 innerHTML atomization problem (in two different ways). Only one blob of code should be responsible for dealing with that IE11 problem, and the one routine should only get called once. The current situation has the tree walked twice.

It's lame that both have to do this, but it's necessary if the custom elements polyfill is going to work both with and without Shady DOM being applied before it. This is specifically the case for some (all?) versions of Safari 10 which included native Shadow DOM support but not native custom elements.

> My simple workaround is to have the custom-elements implementation of innerHTML defensively check isConnected, e.g.

The problem is that it's not necessarily true that `connectedCallback` is only called at a time when an element is connected (and similarly for `disconnectedCallback` when disconnected). The act of connecting an element is the only time that a `connectedCallback` would be queued but that callback might not necessarily be called before the element has been disconnected again.

> That last line's assignment of '' to container.innerHTML is either meant to invoke custom-elements implementation or shadydom's or both.

Both assignments should call into both wrappers.

> My confusion is how could it possibly work to invoke both (meaning custom-elements implementation of innerHTML in turn calls shadydom's implementation, perhaps erroneously thinking it is calling the native implementation of innerHTML?)
>
> Yet if the assignment of '' only called custom-elements implementation, shadydom doesn't get to do whatever it was it wanted to do by patching innerHTML in the first place!

Could you explain why you say that assignment would not result in Shady DOM's `innerHTML` being called? This feels like it might be what's putting us on different pages.

**Comment by Jeff17Robbins** [comment] 2018-01-05 21:10
First of all, thank you (a lot!) for so patiently responding to each and every misconception of mine.  That's really helpful, and I appreciate the implied faith that with careful explanation, eventually I'd "get" it.   And...I think I might (finally) be getting it.  I hope so!

In answer to your question

> Could you explain why you say that assignment would not result in Shady DOM's innerHTML being called? This feels like it might be what's putting us on different pages.

I was mechanically working out the either call custom-element's `innerHTML`, shadydom's `innerHTML`, or call both as 3 scenarios, and my confusing sentence was arguing against a strawman scenario of calling only custom-element's `innerHTML`, a scenario that existed only in my head, and I was pointing out that it would make no sense to _only_ call custom-elements `innerHTML`.  Sorry for my cryptic prose.  

I understand **now** that you are saying that the intent is for a user's call of `innerHTML` to call custom-elements' implementation which, internal to it, then calls shadydom's implementation.  And the bug I found is due to shadydom looping back around when it calls `removeChild` to custom-elements' `removeChild` with its normally helpful side-effect of calling the `disconnectedCallback` reaction.  That is not helpful in this scenario.  And the fix you are suggesting, apparently, is for shadydom not to do that.  

But that fix, to call the native `removeChild`, isn't some generic recipe, which I thought wrongly thought you were proposing, to make sure that every polyfill call to a DOM API would henceforth only call the native version of that API.   That mistaken interpretation on my part led me down the rabbit hole of thinking 

> but... but...  if every patch function everywhere calls the native function (or accessor) it is patching, how on earth will custom-elements's implementation of `innerHTML` call shadydom's?  

The answer I am taking away is that I was misinterpreting, and only _some_ patch functions will call the native implementation.  Others will not.  For example, `clearNode` in shadydom will call the native `removeChild`.  But `innerHTML` in custom-elements will call shadydom's `innerHTML`.  

Is that correct?

**Comment by bicknellr** [comment] 2018-01-05 21:50
> I understand now that you are saying that the intent is for a user's call of innerHTML to call custom-elements' implementation which, internal to it, then calls shadydom's implementation. And the bug I found is due to shadydom looping back around when it calls removeChild to custom-elements' removeChild with its normally helpful side-effect of calling the disconnectedCallback reaction. That is not helpful in this scenario. And the fix you are suggesting, apparently, is for shadydom not to do that.

Yes, that all sounds right.

> But that fix, to call the native removeChild, isn't some generic recipe, which I thought wrongly thought you were proposing, to make sure that every polyfill call to a DOM API would henceforth only call the native version of that API.

So, I am proposing that each polyfill call only APIs as they existed before the polyfill started up. However, I think the key part here is that the things that any given polyfill calls might not be the *native* versions: in the case where someone's using both Shady DOM and the custom elements polyfill, the custom elements polyfill would end up calling Shady DOM's version of any API that Shady DOM wraps because Shady DOM applies those wrappers and puts them back in the right places before the custom elements polyfill goes to find them at startup. (Also, given the way that Shady DOM and the custom elements polyfill work, Shady DOM needs to come before the custom elements polyfill. Otherwise, Shady DOM would have to do significantly more work to adjust effects from the custom elements spec for the way it implements Shadow DOM.)

> The answer I am taking away is that I was misinterpreting, and only some patch functions will call the native implementation. Others will not. For example, clearNode in shadydom will call the native removeChild. But innerHTML in custom-elements will call shadydom's innerHTML.
>
> Is that correct?

Yup! The custom elements polyfill potentially ends up calling into Shady DOM but Shady DOM should only call into what existed before it started up, which shouldn't include anything from the custom elements polyfill.

**Comment by Jeff17Robbins** [comment] 2018-01-08 14:06
I think it is all (finally) sinking in!  Thank you!!!

The "coordination" I was struggling with is actually quite simple:  shadydom must initialize before custom-elements, making shadydom sort of like a "plug-in" for custom-elements, and allowing for the possibility of a browser using shadydom _without_ custom-elements.

One question remains for me.

### quick aside on innerHTML atomization
```
//given elements a, b, and c,
b.appendChild(c);
a.appendChild(b);
document.body.appendChild(a);
a.innerHTML='';
// at this point, on IE11, c is no longer a child of b.  
// The tree linkages underneath a are all removed.  
// Call this "innerHTML atomization".
```

Since AFAIK only IE11 suffers from this innerHTML atomization, and since IE11 needs _both_ polyfills, custom-elements and shadydom, I really don't think both custom-elements and shadydom should have to deal with the atomization in their respective `innerHTML` patches.  Assuming, of course, the the call to `clearNode` in shadydom's `innerHTML` patch is solely dealing with atomization.

Put more simply: why does shadydom need to [call clearNode](https://github.com/webcomponents/shadydom/blob/58da0c19dbf7544e3c7f3fa21f9396892b4ee476/src/patch-accessors.js#L348)  in its `innerHTML` patch?

**Comment by bicknellr** [comment] 2018-01-08 22:34
I think Shady DOM calls `clearNode` there because its `innerHTML` wrapper always uses a secondary element for the call to the wrapped setter: it removes all of `this`' children, sets `innerHTML` on the other element with the given string, and then moves all of the children of the other element to `this`. [The custom elements polyfill does this too](https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/Patch/Element.js#L107-109) but it only happens inside the fake descriptor.

**Comment by Jeff17Robbins** [comment] 2018-01-09 05:19
Thanks @bicknellr, I think I get it now.   I appreciate your explanations.

**Closed** 2019-06-07 23:24 UTC
