### ISSUE TITLE
IE 11 error: Object doesn't support property or method 'call', File: webcomponents-lite.js, Line: 67, Column: 154

### ISSUE THREAD

**Issue by ferroboyd** [webcomponents/custom-elements#103] opened 2017-06-15 19:52 UTC
I made a new default app using the polymer starter kit and I built it using the es5-bundled preset. Will not work in IE11. Works fine in Chrome. Am I not understanding something with the support with polyfills or is this a bug?

Also getting this in console:

 “Unable to get property ‘push’ of undefined or null reference" inside of CustomElementInternal.js (255,7)

**Comment by KamiQuasi** [comment] 2017-06-21 20:04
May not be the exact same issue, but generates the error at will upon press of the "Remove" button (TypeScript transpiled with "none" modules and targeting es5; polyfill doesn't seem to work quite right in jsbin for IE, but the button still throws the same message):
https://jsbin.com/weregew/edit?html,js,console,output

The issue I'm having appears to be centered around this line (https://github.com/webcomponents/custom-elements/blob/master/src/Patch/Interface/ChildNode.js#L104) where, at least in the transpiled  and minified code, the remove function does not exist at that point for IE11. IE11 does get polyfilled for window.Element.prototype.remove, but it doesn't seem like that is being referenced at that point in the code. The easiest way to recreate it is just to create a dummy element in script, transpile to es5, then on the page where you have the element run document.querySelector('dummy-element').remove()

**Comment by bicknellr** [comment] 2017-06-22 22:57
Hi, I've got [a PR](https://github.com/webcomponents/custom-elements/pull/57/files#diff-553e872f48b5a6647db35acb39bb3feeR138) that's been out for a while that fixes this but it hasn't been reviewed unfortunately. :/ @KamiQuasi is right: the problem is that IE11 doesn't support [`remove`](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) but the polyfill adds this method unconditionally. Though, if you're using a polyfill for `remove`, you can put it in first and the custom elements polyfill should end up using the polyfilled `remove`.

**Comment by noamichael** [comment] 2017-06-30 23:43
I'm having the exact same issue. Used the [polyfill from the MDN ](https://github.com/jserz/js_piece/blob/master/DOM/ChildNode/remove()/remove().md) and the exception seems to be gone.

**Comment by bicknellr** [comment] 2017-09-15 17:16
This should be fixed as of tag `v1.0.3`, let me know if it's not!

**Closed by bicknellr** 2017-09-15 17:16 UTC

**Comment by jab** [comment] 2017-10-03 01:04
@bicknellr I just tested a fresh build on a test site that included webcomponentsjs 1.0.14 in IE11, and am seeing this error message. Here's a screenshot:
![screen shot 2017-10-02 at 20 50 01](https://user-images.githubusercontent.com/64992/31105739-39c49c34-a7b4-11e7-8e17-53fad2a0c8b4.png)
Could I still be getting that if this were fixed, or could this be something else? I see https://github.com/webcomponents/webcomponentsjs/issues/830 refers to the same error and is still open, so if that's a separate issue that I'm hitting, I'll track it there instead. (Btw the test site is at https://uproxy.github.io/uproxy.org/ in case it's helpful.)

**Comment by bicknellr** [comment] 2017-10-03 19:01
@jab, the specific error `Object doesn't support property or method 'call'` isn't unique to the particular issue fixed here in v1.0.3, it's just what IE says when you try to reference a property of an object and call it but that function doesn't exist. (For example, you can run `({}).noSuchFunction(1, 2, 3)` in IE's console and it will throw an error with the message `Object doesn't support property or method 'noSuchFunction'`.)

I ran your site and it throws here, inside webcomponents-lite.js:
![screen shot 2017-10-03 at 11 36 16](https://user-images.githubusercontent.com/406614/31142425-1acc9586-a82f-11e7-8ae9-6fb40bc30137.png)
Which looks like it corresponds with this line in ShadyDOM:
https://github.com/webcomponents/shadydom/blob/3d94a2e4cb66563a043e9fc7ca2219e0ff9d8a3e/src/patch-events.js#L360
So the thing it's trying to call the `call` method on isn't a function (and doesn't have a `handleEvent` method). I haven't dug any deeper yet, but I'd double check that you're passing the right kind of thing to the `unload` listener you're setting.

**Comment by srijken** [comment] 2017-10-04 12:43
@bicknellr I'm seeing the exact same error, also on the unload listener. I don't use this listener myself though, so there's probably some other element that does. I tried searching, but haven't found the root cause.

**Comment by web-padawan** [comment] 2017-10-04 12:48
@srijken BTW, `window.onunload` is equal to `null` by default for me, at least in Chrome.

How to check:
1. open `about:blank`
2. open console (F12 in IE)
3. type `window.onunload`

**Comment by srijken** [comment] 2017-10-04 12:59
OK, found the likely culprit. We were still using a 3.x preview of vaadin-grid. Upgraded to released version 3.0.2, and now it works OK in IE11/edge
