### ISSUE TITLE
When using native-shim.js element instanceof HTMLElement returns false for native html elements

### ISSUE THREAD

**Issue by jaroslawsawicki** [webcomponents/custom-elements#32] opened 2016-12-07 11:36 UTC
Steps to reproduce:
1. Load `native-shim.js` 
2. Observe output
```javascript
const element = document.createElement('div');
console.log(element instanceof HTMLElement); //output false
```

**Comment by valdrinkoshi** [comment] 2016-12-07 17:45
Duplicate of https://github.com/webcomponents/webcomponentsjs/issues/623

**Comment by bicknellr** [comment] 2017-02-14 21:38
Fixed as of v1.0.0-alpha.4: http://jsbin.com/revequq/edit?html,console,output

**Closed by bicknellr** 2017-02-14 21:38 UTC

**Comment by bicknellr** [comment] 2017-02-14 21:40
The way the new polyfill handles this is by setting the prototype of the replacement HTMLElement constructor to the old one's prototype. `x instanceof T` is effectively a recursive walk of `x`'s prototype chain to find `T.prototype`, so this ends up working for both custom and built-in elements.
