### ISSUE TITLE
Compiled version of custom-elements.min.js in latest version 1.1.2 does not exist in npm

### ISSUE THREAD

**Issue by barryearles** [webcomponents/custom-elements#165] opened 2018-07-13 20:47 UTC
Hello,

We are trying to install the latest version of custom-elements, but during our `npm compile` step, npm is unable to resolve the `@webcomponents/custom-elements` js.

`Module not found: Error: Cannot resolve module '@webcomponents/custom-elements`

Upon further investigation, we noticed that latest github tag for 1.1.2 contains the `custom-elements.min.js`

https://github.com/webcomponents/custom-elements/tree/v1.1.2

However, npm does not seem to contain the js

https://www.npmjs.com/package/@webcomponents/custom-elements/v/1.1.2

Pre-emptive thanks for looking into this.

**Comment by bicknellr** [comment] 2018-07-25 21:07
I tried retrieving both versions v1.1.2 and v1.1.3 from npm and they each have `custom-elements.min.js`. However, the compiled version of the polyfill was recently removed from the repo itself and is now generated when publishing: https://github.com/webcomponents/custom-elements/pull/160. Are you installing the polyfill though something other than npm?

**Comment by TimvdLippe** [comment] 2018-08-16 10:51
Unable to reproduce as well. Unpkg can also find them on the registry: https://unpkg.com/@webcomponents/custom-elements@1.2.0/ Closing this issue. Feel free to reopen if you can still reproduce this.

**Closed by TimvdLippe** 2018-08-16 10:51 UTC
