### ISSUE TITLE
'native-shim.js' other native elements?

### ISSUE THREAD

**Issue by SerkanSipahi** [webcomponents/custom-elements#29] opened 2016-11-23 08:27 UTC
Its just a question. The native-shim solves only the ES6 (extends HTMLElement) compile to ES5 issue? What about with other "native elements" (see below examles) in customElements v1?

e.g.
```js
class Foo extends HTMLFormElement {}
class Bar extends HTMImageElement {}
class Baz extends HTMLUListElement {}
```
In my current project i use customElements v0 and the above examples works well.

**Comment by snuggs** [comment] 2016-11-26 06:10
@SerkanSipahi there should be no issues as ALL `HTML*Element`s inherit from `HTMLElement`. A call to `super ()` should proliferate up the prototype chain.

![capture d ecran 2016-11-26 a 01 08 55](https://cloud.githubusercontent.com/assets/38223/20638404/f50b28da-b374-11e6-945e-4e3f679c25da.png)

**Comment by SerkanSipahi** [comment] 2016-11-26 09:12
@snuggs im talking about customElement "v1" and not "v0". The `https://github.com/webcomponents` team try to solve the "extends issue" if an es6 code was compiled to es5 in customElements "v1". I saw in the code (https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js#L64) they just adjust only HTMLElement. So my question: if i use the shim, can i extend from 
HTMLFormElement, .., ..., too?

By the way: Your examples (v0) does not work:
```js
let xFoo = class Foo extends HTMLFormElement { 
    constructor() { super() } 
    createdCallback() {console.log('c', this)}
    attachedCallback() {console.log('a', this)}
}

 // Issue: no "createdCallback and attachedCallback" called
let $xFoo1 = document.registerElement('x-foo', Object.create(xFoo.prototype), {extends: 'form'});
let el1 = document.createElement('x-foo');
document.body.append(el1);

 // Issue: no "createdCallback and attachedCallback" called
let $xFoo2 = document.registerElement('x-foo', Object.create(xFoo.prototype), {extends: 'form'});
let el2 = document.createElement('form', 'x-foo');
document.body.append(el2);

```
this works well in v0 with expected behavior (callbacks are called):
```js
class Foo extends HTMLFormElement { 
    createdCallback() {
      console.log('c', this);
      this.innerHTML = `
          <input type="text" name="fname">
          <input type="submit" value="Submit">
      `
    }
    attachedCallback() {console.log('a', this)}
    static get extends() { return 'form' }
}

// example 1:
let $xFoo = document.registerElement('x-foo', Foo);// log 'created' <form is="x-foo"><input .... ></form>

// example 2:
let my elForm = new $xFoo(); // log 'created' <form is="x-foo"><input .... ></form>
document.body.append(elForm) // log 'attached' <form is="x-foo"><input ...></form>
```

this not works (extends like this not work on native elements, i dont know why!?!)
```js 
let $xFoo1 = document.registerElement('x-foo', Foo, {extends: 'form'});
```

**Comment by azakus** [comment] 2019-06-07 23:15
Duplicate of https://github.com/webcomponents/polyfills/issues/102

**Closed by azakus** 2019-06-07 23:15 UTC
